### ISSUE TITLE
this screwed up my original discord install

### ISSUE THREAD

**Issue by Noagi6493** [portapps/discord-portable#127]
#### Steps to reproduce this issue

1. Open the original discord install
2. it works

#### Expected behaviour

> Tell me what should happen

it actually works

#### Actual behaviour

it fails with this log

16120> 2024-06-27 18:26:12> Program: Starting Squirrel Updater: --install . --silent
16120> 2024-06-27 18:26:12> Program: Starting install, writing to C:\Users\monto\AppData\Local\SquirrelTemp
16120> 2024-06-27 18:26:12> Program: About to install to: C:\Users\monto\AppData\Local\Discord
16120> 2024-06-27 18:26:12> SingleGlobalInstance: Grabbing lockfile with timeout of 00:00:10
16120> 2024-06-27 18:26:12> CheckForUpdateImpl: Reading RELEASES file from C:\Users\monto\AppData\Local\SquirrelTemp
16120> 2024-06-27 18:26:13> CheckForUpdateImpl: Remote version 1.0.9003 differs from local 
16120> 2024-06-27 18:26:13> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
16120> 2024-06-27 18:26:13> ApplyReleasesImpl: Writing files to app directory: C:\Users\monto\AppData\Local\Discord\app-1.0.9003
16120> 2024-06-27 18:26:19> ApplyReleasesImpl: Moving file C:\Users\monto\AppData\Local\Discord\app-1.0.9003\lib\net45\chrome_100_percent.pak to C:\Users\monto\AppData\Local\Discord\app-1.0.9003\chrome_100_percent.pak
16120> 2024-06-27 18:26:19> ApplyReleasesImpl: Moving file C:\Users\monto\AppData\Local\Discord\app-1.0.9003\lib\net45\chrome_200_percent.pak to C:\Users\monto\AppData\Local\Discord\app-1.0.9003\chrome_200_percent.pak
16120> 2024-06-27 18:26:19> ApplyReleasesImpl: Moving file C:\Users\monto\AppData\Local\Discord\app-1.0.9003\lib\net45\d3dcompiler_47.dll to C:\Users\monto\AppData\Local\Discord\app-1.0.9003\d3dcompiler_47.dll
16120> 2024-06-27 18:26:19> ApplyReleasesImpl: Moving file C:\Users\monto\AppData\Local\Discord\app-1.0.9003\lib\net45\app.ico to C:\Users\monto\AppData\Local\Discord\app-1.0.9003\app.ico
16120> 2024-06-27 18:26:19> ApplyReleasesImpl: Moving file C:\Users\monto\AppData\Local\Discord\app-1.0.9003\lib\net45\Discord.exe to C:\Users\monto\AppData\Local\Discord\app-1.0.9003\Discord.exe
16120> 2024-06-27 18:26:19> ApplyReleasesImpl: Moving file C:\Users\monto\AppData\Local\Discord\app-1.0.9003\lib\net45\ffmpeg.dll to C:\Users\monto\AppData\Local\Discord\app-1.0.9003\ffmpeg.dll
16120> 2024-06-27 18:26:19> ApplyReleasesImpl: Moving file C:\Users\monto\AppData\Local\Discord\app-1.0.9003\lib\net45\icudtl.dat to C:\Users\monto\AppData\Local\Discord\app-1.0.9003\icudtl.dat
16120> 2024-06-27 18:26:19> ApplyReleasesImpl: Moving file C:\Users\monto\AppData\Local\Discord\app-1.0.9003\lib\net45\installer.db to C:\Users\monto\AppData\Local\Discord\app-1.0.9003\installer.db
16120> 2024-06-27 18:26:19> ApplyReleasesImpl: Moving file C:\Users\monto\AppData\Local\Discord\app-1.0.9003\lib\net45\libEGL.dll to C:\Users\monto\AppData\Local\Discord\app-1.0.9003\libEGL.dll
16120> 2024-06-27 18:26:19> ApplyReleasesImpl: Moving file C:\Users\monto\AppData\Local\Discord\app-1.0.9003\lib\net45\libGLESv2.dll to C:\Users\monto\AppData\Local\Discord\app-1.0.9003\libGLESv2.dll
16120> 2024-06-27 18:26:19> ApplyReleasesImpl: Moving file C:\Users\monto\AppData\Local\Discord\app-1.0.9003\lib\net45\snapshot_blob.bin to C:\Users\monto\AppData\Local\Discord\app-1.0.9003\snapshot_blob.bin
16120> 2024-06-27 18:26:19> ApplyReleasesImpl: Moving file C:\Users\monto\AppData\Local\Discord\app-1.0.9003\lib\net45\resources.pak to C:\Users\monto\AppData\Local\Discord\app-1.0.9003\resources.pak
16120> 2024-06-27 18:26:19> ApplyReleasesImpl: Moving file C:\Users\monto\AppData\Local\Discord\app-1.0.9003\lib\net45\v8_context_snapshot.bin to C:\Users\monto\AppData\Local\Discord\app-1.0.9003\v8_context_snapshot.bin
16120> 2024-06-27 18:26:19> ApplyReleasesImpl: Moving file C:\Users\monto\AppData\Local\Discord\app-1.0.9003\lib\net45\vk_swiftshader.dll to C:\Users\monto\AppData\Local\Discord\app-1.0.9003\vk_swiftshader.dll
16120> 2024-06-27 18:26:19> ApplyReleasesImpl: Moving file C:\Users\monto\AppData\Local\Discord\app-1.0.9003\lib\net45\updater.node to C:\Users\monto\AppData\Local\Discord\app-1.0.9003\updater.node
16120> 2024-06-27 18:26:19> ApplyReleasesImpl: Moving file C:\Users\monto\AppData\Local\Discord\app-1.0.9003\lib\net45\vk_swiftshader_icd.json to C:\Users\monto\AppData\Local\Discord\app-1.0.9003\vk_swiftshader_icd.json
16120> 2024-06-27 18:26:19> ApplyReleasesImpl: Moving file C:\Users\monto\AppData\Local\Discord\app-1.0.9003\lib\net45\vulkan-1.dll to C:\Users\monto\AppData\Local\Discord\app-1.0.9003\vulkan-1.dll
16120> 2024-06-27 18:26:20> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\monto\AppData\Local\Discord\app-1.0.9003\Discord.exe]
16120> 2024-06-27 18:26:32> Utility: Process Started: C:\Users\monto\AppData\Local\Discord\app-1.0.9003\Discord.exe --squirrel-install 1.0.9003, pid 15824
16120> 2024-06-27 18:26:39> Utility: Received exitcode 0 from process C:\Users\monto\AppData\Local\Discord\app-1.0.9003\Discord.exe
16120> 2024-06-27 18:26:39> ApplyReleasesImpl: Starting fixPinnedExecutables
16120> 2024-06-27 18:26:39> ApplyReleasesImpl: fixPinnedExecutables: newCurrentFolder: app-1.0.9003
16120> 2024-06-27 18:26:39> ApplyReleasesImpl: File 'C:\Users\monto\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Accessibility\LiveCaptions.lnk' could not be converted into a valid ShellLink: System.IO.FileNotFoundException: The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
   at Squirrel.Shell.ShellLink.IShellLinkW.Resolve(IntPtr hWnd, UInt32 fFlags)
   at Squirrel.Shell.ShellLink.Open(String linkFile, IntPtr hWnd, EShellLinkResolveFlags resolveFlags, UInt16 timeOut)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<fixPinnedExecutables>b__11_0(FileInfo file)
16120> 2024-06-27 18:26:39> ApplyReleasesImpl: File 'C:\Users\monto\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Accessibility\Narrator.lnk' could not be converted into a valid ShellLink: System.IO.FileNotFoundException: The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
   at Squirrel.Shell.ShellLink.IShellLinkW.Resolve(IntPtr hWnd, UInt32 fFlags)
   at Squirrel.Shell.ShellLink.Open(String linkFile, IntPtr hWnd, EShellLinkResolveFlags resolveFlags, UInt16 timeOut)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<fixPinnedExecutables>b__11_0(FileInfo file)
16120> 2024-06-27 18:26:39> ApplyReleasesImpl: File 'C:\Users\monto\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Accessibility\On-Screen Keyboard.lnk' could not be converted into a valid ShellLink: System.IO.FileNotFoundException: The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
   at Squirrel.Shell.ShellLink.IShellLinkW.Resolve(IntPtr hWnd, UInt32 fFlags)
   at Squirrel.Shell.ShellLink.Open(String linkFile, IntPtr hWnd, EShellLinkResolveFlags resolveFlags, UInt16 timeOut)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<fixPinnedExecutables>b__11_0(FileInfo file)
16120> 2024-06-27 18:26:39> ApplyReleasesImpl: File 'C:\Users\monto\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Accessibility\VoiceAccess.lnk' could not be converted into a valid ShellLink: System.IO.FileNotFoundException: The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
   at Squirrel.Shell.ShellLink.IShellLinkW.Resolve(IntPtr hWnd, UInt32 fFlags)
   at Squirrel.Shell.ShellLink.Open(String linkFile, IntPtr hWnd, EShellLinkResolveFlags resolveFlags, UInt16 timeOut)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<fixPinnedExecutables>b__11_0(FileInfo file)
16120> 2024-06-27 18:26:39> ApplyReleasesImpl: Updating shortcut C:\Users\monto\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Discord Inc\Discord.lnk
16120> 2024-06-27 18:26:39> ApplyReleasesImpl: Updating shortcut C:\Users\monto\OneDrive\Desktop\Discord.lnk
16120> 2024-06-27 18:26:39> ApplyReleasesImpl: Fixing up tray icons
16120> 2024-06-27 18:26:39> ApplyReleasesImpl: cleanDeadVersions: for version 1.0.9003
16120> 2024-06-27 18:26:39> ApplyReleasesImpl: cleanDeadVersions: exclude current version folder app-1.0.9003
26676> 2024-11-17 13:43:10> Program: Starting Squirrel Updater: --install . --silent
26676> 2024-11-17 13:43:10> Program: Starting install, writing to C:\Users\monto\AppData\Local\SquirrelTemp
26676> 2024-11-17 13:43:10> Program: About to install to: C:\Users\monto\AppData\Local\Discord
26676> 2024-11-17 13:43:10> Program: Install path C:\Users\monto\AppData\Local\Discord already exists, burning it to the ground
26676> 2024-11-17 13:43:10> IEnableLogger: Failed to remove existing directory on full install, is the app still running???: System.IO.IOException: Access to the path 'C:\Users\monto\AppData\Local\Discord' is denied.
   at System.IO.Directory.InternalMove(String sourceDirName, String destDirName, Boolean checkHost)
   at Squirrel.Utility.<DeleteDirectory>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__37.MoveNext()
26676> 2024-11-17 13:43:10> Unhandled exception: System.AggregateException: One or more errors occurred. ---> System.IO.IOException: Access to the path 'C:\Users\monto\AppData\Local\Discord' is denied.
   at System.IO.Directory.InternalMove(String sourceDirName, String destDirName, Boolean checkHost)
   at Squirrel.Utility.<DeleteDirectory>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__37.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Update.Program.<Install>d__5.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
---> (Inner Exception #0) System.IO.IOException: Access to the path 'C:\Users\monto\AppData\Local\Discord' is denied.
   at System.IO.Directory.InternalMove(String sourceDirName, String destDirName, Boolean checkHost)
   at Squirrel.Utility.<DeleteDirectory>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__37.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Update.Program.<Install>d__5.MoveNext()<---

20536> 2024-11-17 13:46:15> Program: Starting Squirrel Updater: --install .
20536> 2024-11-17 13:46:15> Program: Starting install, writing to C:\Users\monto\AppData\Local\SquirrelTemp
20536> 2024-11-17 13:46:15> Program: About to install to: C:\Users\monto\AppData\Local\Discord
20536> 2024-11-17 13:46:15> Program: Install path C:\Users\monto\AppData\Local\Discord already exists, burning it to the ground
20536> 2024-11-17 13:46:15> IEnableLogger: Failed to remove existing directory on full install, is the app still running???: System.IO.IOException: Access to the path 'C:\Users\monto\AppData\Local\Discord' is denied.
   at System.IO.Directory.InternalMove(String sourceDirName, String destDirName, Boolean checkHost)
   at Squirrel.Utility.<DeleteDirectory>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__37.MoveNext()
20536> 2024-11-17 13:46:15> Unhandled exception: System.AggregateException: One or more errors occurred. ---> System.IO.IOException: Access to the path 'C:\Users\monto\AppData\Local\Discord' is denied.
   at System.IO.Directory.InternalMove(String sourceDirName, String destDirName, Boolean checkHost)
   at Squirrel.Utility.<DeleteDirectory>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__37.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Update.Program.<Install>d__5.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
---> (Inner Exception #0) System.IO.IOException: Access to the path 'C:\Users\monto\AppData\Local\Discord' is denied.
   at System.IO.Directory.InternalMove(String sourceDirName, String destDirName, Boolean checkHost)
   at Squirrel.Utility.<DeleteDirectory>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__37.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Update.Program.<Install>d__5.MoveNext()<---

25256> 2024-11-17 13:47:05> Program: Starting Squirrel Updater: --install .
25256> 2024-11-17 13:47:05> Program: Starting install, writing to C:\Users\monto\AppData\Local\SquirrelTemp
25256> 2024-11-17 13:47:05> Program: About to install to: C:\Users\monto\AppData\Local\Discord
25256> 2024-11-17 13:47:05> Program: Install path C:\Users\monto\AppData\Local\Discord already exists, burning it to the ground
25256> 2024-11-17 13:47:05> IEnableLogger: Failed to remove existing directory on full install, is the app still running???: System.IO.IOException: Access to the path 'C:\Users\monto\AppData\Local\Discord' is denied.
   at System.IO.Directory.InternalMove(String sourceDirName, String destDirName, Boolean checkHost)
   at Squirrel.Utility.<DeleteDirectory>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__37.MoveNext()
25256> 2024-11-17 13:47:05> Unhandled exception: System.AggregateException: One or more errors occurred. ---> System.IO.IOException: Access to the path 'C:\Users\monto\AppData\Local\Discord' is denied.
   at System.IO.Directory.InternalMove(String sourceDirName, String destDirName, Boolean checkHost)
   at Squirrel.Utility.<DeleteDirectory>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__37.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Update.Program.<Install>d__5.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
---> (Inner Exception #0) System.IO.IOException: Access to the path 'C:\Users\monto\AppData\Local\Discord' is denied.
   at System.IO.Directory.InternalMove(String sourceDirName, String destDirName, Boolean checkHost)
   at Squirrel.Utility.<DeleteDirectory>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__37.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Update.Program.<Install>d__5.MoveNext()<---

> Tell me what happens instead

### Configuration

**App release / arch (ex. 1.0.0-2 win64)** :

**Operating system (ex. Windows 10 Pro 64 bits)** :

**Winver screenshot** :

> Open a command prompt and type winver then take / save the screenshot of the window and drag the image file in this issue. For example: http://bit.ly/2vA5sxR
![image](https://github.com/user-attachments/assets/4af62374-b392-4d29-8ee8-9a8d2e7f7f92)

### Screenshots

> If applicable, add screenshots to help explain your problem.

### Logs

Join the log file `log\[appname]-portable.log` to this issue.

**Comment by Noagi6493** [comment]
Edit: i fixed it but still screw this software
